import { useParams, Link } from "react-router-dom";
import { Phone, MessageSquare, Video, Brain, ArrowLeft, ArrowUpRight, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const featuresData = {
  "voice-analysis": {
    icon: Phone,
    number: "01",
    title: "VOICE & CALL ANALYSIS",
    subtitle: "Real-time voice authentication",
    description: "Advanced voice verification that runs entirely on your device, detecting AI-generated or cloned voices with unprecedented accuracy.",
    capabilities: [
      { title: "AI Voice Detection", detail: "Identifies synthetic voices generated by AI systems like ElevenLabs, Resemble AI, and others" },
      { title: "Clone Recognition", detail: "Detects when a voice has been cloned from samples, even with just a few seconds of original audio" },
      { title: "Pitch Analysis", detail: "Analyzes unnatural pitch stability that humans cannot produce naturally" },
      { title: "Breath Pattern Detection", detail: "Identifies missing or artificial breath patterns in synthetic speech" },
      { title: "Latency Artifact Detection", detail: "Spots processing delays and artifacts introduced by real-time voice conversion" },
      { title: "Emotional Mismatch Flagging", detail: "Detects when emotional tone doesn't match speech content or context" },
    ],
    useCases: [
      "Protect against grandparent scams",
      "Verify caller identity in financial transactions",
      "Authenticate voice messages from known contacts",
      "Screen unknown callers for AI manipulation",
    ],
  },
  "message-verification": {
    icon: MessageSquare,
    number: "02",
    title: "MESSAGE VERIFICATION",
    subtitle: "AI text detection",
    description: "Distinguish between human and AI-written content instantly, protecting against sophisticated phishing and impersonation attempts.",
    capabilities: [
      { title: "AI Text Detection", detail: "Identifies content generated by ChatGPT, Claude, and other large language models" },
      { title: "Typing Pattern Analysis", detail: "Analyzes typing rhythms and patterns unique to human composition" },
      { title: "Linguistic Entropy", detail: "Measures the randomness and creativity in text that AI struggles to replicate" },
      { title: "Repetition Detection", detail: "Flags unusual repetitive patterns common in AI-generated content" },
      { title: "Intent Anomaly Detection", detail: "Identifies manipulative intent patterns in messages" },
      { title: "Impersonation Flagging", detail: "Detects CEO fraud, fake relatives, and scam attempts" },
    ],
    useCases: [
      "Prevent CEO fraud wire transfer scams",
      "Detect phishing emails",
      "Verify authenticity of important communications",
      "Screen messages for manipulation attempts",
    ],
  },
  "video-integrity": {
    icon: Video,
    number: "03",
    title: "VIDEO & MEDIA INTEGRITY",
    subtitle: "Deepfake detection",
    description: "Comprehensive deepfake and manipulation detection that analyzes video content frame-by-frame to ensure authenticity.",
    capabilities: [
      { title: "Deepfake Detection", detail: "Identifies AI-generated faces and manipulated video content" },
      { title: "Face Swap Recognition", detail: "Detects when a face has been swapped onto another person's body" },
      { title: "Lip-Sync Analysis", detail: "Identifies when audio has been manipulated to match lip movements" },
      { title: "Frame Inconsistency Detection", detail: "Spots artifacts and inconsistencies between video frames" },
      { title: "Micro-Expression Analysis", detail: "Analyzes subtle facial movements that are difficult to fake" },
      { title: "Eye Movement Tracking", detail: "Detects unnatural eye movements common in synthetic videos" },
    ],
    useCases: [
      "Verify video call participants",
      "Authenticate video evidence",
      "Screen social media content",
      "Protect against video-based fraud",
    ],
  },
  "contextual-check": {
    icon: Brain,
    number: "04",
    title: "CONTEXTUAL REALITY CHECK",
    subtitle: "Multi-signal analysis",
    description: "Cross-checks interaction behavior against known human patterns using device sensors for comprehensive plausibility analysis.",
    capabilities: [
      { title: "Behavioral Pattern Matching", detail: "Compares interaction patterns against known human behavior databases" },
      { title: "Device Sensor Integration", detail: "Uses time, motion, and interaction flow data for verification" },
      { title: "Context Analysis", detail: "Evaluates plausibility based on situational context" },
      { title: "Trust Score Generation", detail: "Builds comprehensive trust scores from multiple signals" },
      { title: "Historical Comparison", detail: "Compares current interactions against established patterns" },
      { title: "Anomaly Detection", detail: "Flags unusual deviations from normal interaction patterns" },
    ],
    useCases: [
      "Comprehensive identity verification",
      "Multi-factor authentication enhancement",
      "Continuous trust monitoring",
      "Anomalous behavior detection",
    ],
  },
};

const FeatureDetail = () => {
  const { slug } = useParams<{ slug: string }>();
  const feature = slug ? featuresData[slug as keyof typeof featuresData] : null;

  if (!feature) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <div className="pt-32 container mx-auto px-4 text-center">
          <h1 className="font-display text-4xl font-bold mb-4">Feature Not Found</h1>
          <Link to="/features">
            <Button>Back to Features</Button>
          </Link>
        </div>
        <Footer />
      </div>
    );
  }

  const Icon = feature.icon;

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      {/* Hero */}
      <section className="pt-32 pb-20 relative overflow-hidden">
        <div className="absolute inset-0 bg-geometric opacity-30" />
        <div className="absolute -right-20 top-0 font-display text-[25vw] font-bold text-foreground/[0.02] select-none pointer-events-none leading-none">
          {feature.number}
        </div>
        
        <div className="container mx-auto px-4 md:px-6 relative z-10">
          {/* Back link */}
          <Link to="/features" className="inline-flex items-center gap-2 text-xs font-mono uppercase tracking-wider text-muted-foreground hover:text-primary transition-colors mb-8">
            <ArrowLeft className="w-4 h-4" />
            Back to Features
          </Link>
          
          <div className="max-w-3xl">
            <div className="flex items-center gap-6 mb-8">
              <div className="w-20 h-20 border-2 border-primary flex items-center justify-center">
                <Icon className="w-9 h-9 text-primary" />
              </div>
              <span className="font-display text-6xl font-bold text-foreground/10">{feature.number}</span>
            </div>
            
            <h1 className="font-display text-4xl md:text-5xl lg:text-6xl font-bold leading-[0.9] mb-4 reveal">
              {feature.title}
            </h1>
            <p className="text-xs font-mono uppercase tracking-widest text-primary mb-6">{feature.subtitle}</p>
            <p className="text-lg text-muted-foreground font-mono leading-relaxed max-w-xl">
              {feature.description}
            </p>
          </div>
        </div>
      </section>

      {/* Capabilities */}
      <section className="py-20 bg-card">
        <div className="container mx-auto px-4 md:px-6">
          <div className="mb-12">
            <div className="flex items-center gap-4 mb-6">
              <span className="w-16 h-px bg-primary" />
              <span className="text-xs font-mono uppercase tracking-widest text-primary">Capabilities</span>
            </div>
            <h2 className="font-display text-3xl md:text-4xl font-bold">
              WHAT IT <span className="text-gradient">DETECTS</span>
            </h2>
          </div>

          <div className="grid md:grid-cols-2 gap-px bg-border">
            {feature.capabilities.map((cap, index) => (
              <div key={index} className="bg-background p-8 group hover:bg-secondary/30 transition-colors">
                <div className="flex items-start gap-4">
                  <span className="text-primary font-mono text-sm">0{index + 1}</span>
                  <div>
                    <h3 className="font-display font-bold text-lg mb-2">{cap.title}</h3>
                    <p className="text-sm text-muted-foreground font-mono">{cap.detail}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Use Cases */}
      <section className="py-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-3xl mx-auto">
            <div className="mb-12 text-center">
              <h2 className="font-display text-3xl md:text-4xl font-bold">
                PERFECT <span className="text-gradient">FOR</span>
              </h2>
            </div>

            <div className="space-y-4">
              {feature.useCases.map((useCase, index) => (
                <div key={index} className="flex items-center gap-4 p-4 border-2 border-foreground/10 hover:border-primary/50 transition-colors">
                  <CheckCircle className="w-5 h-5 text-primary flex-shrink-0" />
                  <span className="font-mono">{useCase}</span>
                </div>
              ))}
            </div>

            <div className="text-center mt-12">
              <Link to="/demo">
                <Button className="font-mono uppercase text-xs tracking-wider h-14 px-10 border-2 border-primary bg-primary text-primary-foreground hover:bg-transparent hover:text-primary transition-all hover-brutal">
                  Try Demo
                  <ArrowUpRight className="w-4 h-4 ml-2" />
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default FeatureDetail;